/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_catnies_simplelib_SimpleLibSource */

#ifndef _Included_top_catnies_simplelib_SimpleLibSource
#define _Included_top_catnies_simplelib_SimpleLibSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_catnies_simplelib_SimpleLibSource
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_catnies_simplelib_SimpleLibSource_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
